old/SecretSanta/Backup/SecretSanta.WebUI/Controllers/Admin/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Castle.MicroKernel.SubSystems.Conversion;
using SecretSanta.Core.ApplicationServices.Interfaces;
using SecretSanta.Core.Domain;
using SecretSanta.WebUI.Controllers.Admin.QueryModels;
using SecretSanta.WebUI.Controllers.Admin.ViewModels;

namespace SecretSanta.WebUI.Controllers.Admin
{
    public class AdminController : Controller
    {
        private readonly IUserService _userService;
        private readonly IGroupService _groupService;
        private readonly IEmailService _emailService;

        public AdminController(IUserService userService, IGroupService groupService, IEmailService emailService)
        {
            _userService = userService;
            _groupService = groupService;
            _emailService = emailService;
        }

        public ActionResult Index()
        {
            return UserOverview();
        }

        public ActionResult UserOverview()
        {
            var model = new UserOVerviewModelView
            {
                Users = _userService.GetAllUsers()
            };
            return View("UserOVerview",model);
        }

        public ActionResult GroupOverview()
        {
            var groups = _groupService.GetAllGroups();
            var model = new GroupOverviewViedModel
            {
                GroupViewModels = groups.Select(group=> new GroupViewModel()
                {
                    Name = group.Name,
                    UserNames = group.UserIds.Select(x => _userService.GetUser(x).UserName).ToList(),
                    AdminUserNames = group.AdminUserIds.Select(x=>_userService.GetUser(x).UserName).ToList(),
                    BlacklistedPairs = group.BlacklistedPairs.Select(UserPairToUserNamePair).ToList(),
                    GeneratedPairs = group.GeneratedPairs.Select(UserPairToUserNamePair).ToList(),
                    Id = group.Id,
                    Started = group.Started
                }).ToList()
            };
            return View("GroupOverview", model);
        }


        [HttpPost]
        public JsonResult SaveOrUpdateUser(User user)
        {
            _userService.SaveUser(user);
            return Json("ok");
        }

        [HttpPost]
        public ActionResult DeleteUser(int userId)
        {
            _userService.DeleteUser(userId);
            return RedirectToAction("UserOverview");
        }

        public ActionResult ClearUserInbox(int userId)
        {
            throw new NotSupportedException();
            return RedirectToAction("UserOverview");
        }

        public ActionResult AddNewUser()
        {
            var user = new User();
            _userService.SaveUser(user);
            return RedirectToAction("UserOverview");

        }


        [HttpPost]
        public JsonResult SaveOrUpdateGroup(GroupQueryModel groupQueryModel)
        {
            var inputUsers = groupQueryModel.UserNames.SelectMany(x => x.Split(new char[] {',', ';'})).ToList();
            var inputAdmins= groupQueryModel.AdminUserNames.SelectMany(x => x.Split(new char[] { ',', ';' })).ToList();

            var users = inputUsers.Select(x => _userService.GetUser(x.Trim())).Where(x => x != null);
            var admins = inputAdmins.Select(x => _userService.GetUser(x.Trim())).Where(x => x != null);
            var blackList = GenerateBlacklist(groupQueryModel).ToList();
            var group = new Group()
            {
                Name = groupQueryModel.GroupName,
                UserIds = users.Select(x=>x.Id).ToList(),
                AdminUserIds = admins.Select(x=>x.Id).ToList(),
                BlacklistedPairs = blackList.Select(UserNamePairToUserPair).ToList(),
                Id = groupQueryModel.Id
            };
            _groupService.SaveGroup(group);
            return Json("ok");
        }

        [HttpPost]
        public ActionResult DeleteGroup(int groupId)
        {
            _groupService.DeleteGroup(groupId);
           return RedirectToAction("GroupOverview");

        }

        public ActionResult AddNewGroup()
        {
           
            _groupService.SaveGroup(new Group()); 
            return RedirectToAction("GroupOverview");

        }

        public ActionResult StartGroup(int groupId)
        {
            var group = _groupService.GetGroup(groupId);
            if (group == null)
                return GroupOverview();
            group.GeneratedPairs = _groupService.GenerateUserPairs(group);
            group.Started = DateTime.Now;
            _groupService.SaveGroup(group);

            var gameUrl = Request.Url.GetLeftPart(UriPartial.Authority);
            //_emailService.SendLoginEmails(group, group.UserIds.Select(id => _userService.GetUser(id)).ToList(), gameUrl);
            return RedirectToAction("GroupOverview");
        }

        //Fugly, fix
        private UserNamePair UserPairToUserNamePair(UserPair userpair)
        {
            return new UserNamePair()
            {
                ReceiverUserName = _userService.GetUser(userpair.ReceiverId).UserName,
                SecretSantaUserName = _userService.GetUser(userpair.SecretSantaId).UserName
            };
        }
        private UserPair UserNamePairToUserPair(UserNamePair usernamePair)
        {
            return new UserPair()
            {
                ReceiverId = _userService.GetUser(usernamePair.ReceiverUserName).Id,
                SecretSantaId = _userService.GetUser(usernamePair.SecretSantaUserName).Id

            };
        }

        private IEnumerable<UserNamePair> GenerateBlacklist(GroupQueryModel groupQueryModel)
        {
             var blackListPairStrings = groupQueryModel.BlacklistedUserPairs.SelectMany(x => x.Split(new char[] {','})).ToList();
            foreach (var blackListPairString in blackListPairStrings)
            {
                var mutliWayTokens = blackListPairString.Split(new string[] { "<->" }, StringSplitOptions.RemoveEmptyEntries);
                if (mutliWayTokens.Length == 2)
                {
                    yield return new UserNamePair()
                    {
                        SecretSantaUserName = (mutliWayTokens[0].Trim()),
                        ReceiverUserName = (mutliWayTokens[1].Trim())
                    };
                    yield return new UserNamePair()
                    {
                        SecretSantaUserName = (mutliWayTokens[1].Trim()),
                        ReceiverUserName = (mutliWayTokens[0].Trim())
                    };
                }
                else
                {
                       var tokens = blackListPairString.Split(new string[] { "->" }, StringSplitOptions.RemoveEmptyEntries);
                if (tokens.Length != 2)
                    continue;
                yield return new UserNamePair()
                {
                    SecretSantaUserName = (tokens[0].Trim()),
                    ReceiverUserName =(tokens[1].Trim())
                };
                }
            }
              
                
             
        } 

    }
}

old/SecretSanta/Backup/SecretSanta.WebUI/Views/Admin/GroupOverview.cshtml
@using System.Web.UI.WebControls
@using SecretSanta.Core.Domain
@model SecretSanta.WebUI.Controllers.Admin.ViewModels.GroupOverviewViedModel

@{
    ViewBag.Title = "Add or Edit groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
$(document).ready(function () {
    $('.editable').editable({
        url: "SaveOrUpdateGroup",
        send: "always",
        mode: "popup",
        ajaxOptions: {
            contentType: 'application/json'
        },
        select2: {
            tokenSeparators: [","],
            tags: [],
            width: "resolve"
        },
        params: function (params) {

            var data = {};
            var editables = $(this).parents("tr").find("a");
            var activeEdit = $(this);
            $(editables).each(function () {

                var paramName = $(this).attr("name");
                if (paramName == "UserNames") {
                    data[paramName] = (activeEdit.attr("name") == "UserNames" ? params.value : $(this).text().split(","));
                }
                else if (paramName == "BlacklistedUserPairs") {
                    data[paramName] = (activeEdit.attr("name") == "BlacklistedUserPairs" ? params.value : $(this).text().split(","));
                } 
                else {
                    data[paramName] = (activeEdit.attr("name") == paramName ? params.value : $(this).text());
                }   
            });
            return JSON.stringify(data);
        }
    });
});
</script>



<h2>@ViewBag.Title</h2>
<div class="well-lg background-color-white">
    <table class="table table-bordered table-striped snowfallCollector"  >
        <thead>
            <tr>
                <th>Group name</th>
                <th>Users</th>
                <th>Blacklisted users</th>
                <th>Action</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var group in Model.GroupViewModels)
            {
                <tr>
                    <td><a href="#" class="editable" data-type="text" data-title="Enter group name" name="GroupName">@group.Name</a></td>
                    <td><a href="#" class="editable" data-type="text" data-title="Add users by their user names" name="UserNames">@string.Join(",", group.UserNames)</a></td>
                    <td><a href="#" class="editable" data-type="text" data-title="Add blacklist pairs" name="BlacklistedUserPairs">
                            @string.Join(",", group.BlacklistedPairs.Select(x=>x.SecretSantaUserName + " -> " +x.ReceiverUserName))
                        </a>
                    </td>
                    <td>
                        @if (group.Started.HasValue)
                        {
                            <p>Started @group.Started.Value</p>
                             @Html.ActionLink("Restart group", "StartGroup", new { groupId = group.Id})
                        }
                        else
                        {
                            <p>Not started</p>
                             @Html.ActionLink("Start group", "StartGroup", new { groupId= group.Id})
                        }
                       
                    </td>
                    <td style="width:1%">
                        @using (Html.BeginForm("DeleteGroup", "Admin", FormMethod.Post, new { @class = "text-center", style = "margin-bottom: 0px;" }))
                        {
                            <input type="hidden" name="groupId" value="@group.Id" />
                            <button type="submit" class="btn btn-mini btn-danger"><i class="glyphicon-trash"> </i></button>
                        }
                    </td>
                    <td class="hidden"> <a name="id">@group.Id</a></td>
                </tr>
            }
        </tbody>
    </table>

    <div class="row-fluid">
        

        @using (Html.BeginForm("AddNewGroup", "Admin", FormMethod.Post))
        {
          <input type="submit" class="btn btn-primary" value="Add group"/>  
        }                                                                             
    </div>
</div>

old/SecretSanta/Backup/SecretSanta.WebUI/Views/Admin/UserOverview.cshtml
@model SecretSanta.WebUI.Controllers.Admin.ViewModels.UserOVerviewModelView

@{
    ViewBag.Title = "Add or Edit users";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
$(document).ready(function () {
    $('.editable').editable({
        url: "SaveOrUpdateUser",
        send: "always",
        mode: "popup",
        ajaxOptions: {
            contentType: 'application/json'
        },
        select2: {
            tokenSeparators: [","],
            tags: [],
            width: "resolve"
        },
        params: function (params) {

            var data = {};
            var editables = $(this).parents("tr").find("a");
            var activeEdit = $(this);
            $(editables).each(function () {
                var paramName = $(this).attr("name");
                    data[paramName] = (activeEdit.attr("name") == paramName ? params.value : $(this).text());
               
            });
            return JSON.stringify(data);
        }
    });
});
</script>




<h2>@ViewBag.Title</h2>
<div class="well-lg background-color-white">
    <table class="table table-bordered table-striped snowfallCollector">
        <thead>
            <tr>
                <th>Username</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Email</th>
                <th>Password</th>
                <th>Last login</th>
                <th>Clear inbox</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var user in Model.Users)
            {
                <tr>
                    <td><a href="#" class="editable" data-type="text" data-title="Enter Username" name="userName">@user.UserName</a></td>
                    <td><a href="#" class="editable" data-type="text" data-title="Enter first name" name="firstName">@user.FirstName</a></td>
                    <td><a href="#" class="editable" data-type="text" data-title="Enter sur name" name="lastName">@user.LastName</a></td>
                    <td><a href="#" class="editable" data-type="text" data-title="Enter email adress" name="email">@user.Email</a></td>
                    <td><a href="#" class="editable" data-type="text" data-title="Enter password" name="password">@user.Password</a></td>
                    <td><a href="#" data-type="text"  name="lastLoginDate">@user.LastLoginDate</a></td>
                    
@*
                    <td style="width:1%">
                        @using (Html.BeginForm("ClearUserInbox", "Admin", FormMethod.Post, new { @class = "text-center", style = "margin-bottom: 0px;" }))
                        {
                            <input type="hidden" name="userId" value="@user.Id" />
                            <button type="submit" class="btn btn-sm btn-warning"><i class="glyphicon-trash"> </i></button>
                        }
                    </td>*@
                    <td style="width:1%">
                        @using (Html.BeginForm("DeleteUSer", "Admin", FormMethod.Post, new { @class = "text-center", style = "margin-bottom: 0px;" }))
                        {
                            <input type="hidden" name="userId" value="@user.Id" />
                            <button type="submit" class="btn btn-sm btn-danger"><i class="glyphicon-trash"> </i></button>
                        }
                    </td>
                    <td><a class="hidden" name="id">@user.Id</a></td>
                </tr>
            }
        </tbody>
    </table>

    <div class="row-fluid">
        

        @using (Html.BeginForm("AddNewUser", "Admin", FormMethod.Post))
        {
          <input type="submit" class="btn btn-primary" value="Add user"/>  
        }                                                                             
    </div>
</div>