api/SecretSanta/Controllers/Game/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Authentication;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SecretSanta.Core.ApplicationServices.Interfaces;
using SecretSanta.Core.Domain;
using SecretSanta.RazorWebUI.Attributes;
using SecretSanta.WebUI.Controllers.Game.Domain;
using SecretSanta.WebUI.Controllers.Game.ModelMappers;
using SecretSanta.WebUI.Controllers.Game.QueryModels;
using SecretSanta.WebUI.Controllers.Game.ViewModels;

namespace SecretSanta.RazorWebUI.Controllers.Game
{
    [Authorize]
    public class GameController : Controller
    {
        private readonly IUserService _userService;
        private readonly IGroupService _groupService;
        private readonly IGamePageModelMapper _gamePageMapper;


        public GameController(IUserService userService, IGroupService groupService, IGamePageModelMapper gamePageMapper){
            _userService = userService;
            _groupService = groupService;
            _gamePageMapper = gamePageMapper;
        }


        //[RequireLogin]
        [Route("")]
        [Route("Game/GamePage")]
        public ActionResult GamePage(string currentGroup = "",string currentTab ="")
        {
            var loggedInUser = _userService.GetUser(HttpContext.User.Identity.Name);
            if (loggedInUser == null)
                throw new AuthenticationException("No user named " + HttpContext.User.Identity.Name + " found");

            var availableGroups = _groupService.GetGroupsForUser(loggedInUser.UserName);
            if (!availableGroups.Any() || !availableGroups.Any(x => x.IsStarted()))
                return View("NoGroup", loggedInUser);
            
            var selectedGroup = new CurrentGroup()
            {
                Group = availableGroups.FirstOrDefault(x => x.Name == currentGroup) ?? availableGroups.FirstOrDefault()
            };
            selectedGroup.GroupMessages = _groupService.GetGroupMessages(selectedGroup.Group.Id, 150);
            var linkedUser = GetLinkedUsers(loggedInUser, selectedGroup.Group);

            var model = new GamePageViewModel
            {
                CurrentGroup = selectedGroup.Group.Name,
                CurrentTab = currentTab,
                GroupChatPresenterViewModel =
                    _gamePageMapper.MapGroupChatPresenter(
                    loggedInUser, selectedGroup.Group, selectedGroup.GroupMessages, 
                    selectedGroup.Group.UserIds.Select(userId => _userService.GetUser(userId)).ToList()),
                LoggedInUser = loggedInUser,
                MenuViewModel = new MenuViewModel()
                {
                    GameGroupMenuViewModel = _gamePageMapper.MapGameGroupMenu(availableGroups, selectedGroup.Group)
                },
                ReceivingUserPresenterViewModel =
                    _gamePageMapper.MapReceivingUserViewModel(linkedUser, selectedGroup.Group,
                        _userService.GetWishes(linkedUser.ReceiverUser.Id)),
                UserWishlistPresenterViewModel =
                    _gamePageMapper.MapUserWishlist(linkedUser,_userService.GetWishes(loggedInUser.Id))
            };
            return View("GamePage",model);
        }



        [RequireLogin]
        public string StartGameForUser()
        {
            var user = GetLoggedInUser();
            user.LastLoginDate = DateTime.Now;
            _userService.SaveUser(user);
            return "Kör på!";
        }

        

        [RequireLogin]
        public JsonResult SaveOrUpdateWish(WishQueryModel wishQueryModel)
        {
            var loggedInUser = GetLoggedInUser();
            var wish = new Wish()
            {
                Description = wishQueryModel.Wish,
                Id = wishQueryModel.WishId
            };

            _userService.SaveWish(wish, loggedInUser.Id);
            return Json("ok");
        }

        [RequireLogin]
        public ActionResult AddWish(WishQueryModel wishQueryModel)
        {
            var loggedInUser = GetLoggedInUser();
            var wish = new Wish()
            {
                Description = wishQueryModel.Wish,
                Id = wishQueryModel.WishId
            };
            _userService.SaveWish(wish, loggedInUser.Id);
            return RedirectToAction("GamePage", new { currentGroup = wishQueryModel.CurrentGroup, currentTab = wishQueryModel.CurrentTab });
        }

        [RequireLogin]
        public ActionResult DeleteWish(WishQueryModel wishQueryModel)
        {
            var loggedInUser = GetLoggedInUser();

            _userService.DeleteWish(wishQueryModel.WishId,loggedInUser.Id);
            return RedirectToAction("GamePage", new { currentGroup = wishQueryModel.CurrentGroup, currentTab = wishQueryModel.CurrentTab });

        }

       
        [RequireLogin]
        public ActionResult SendUserMessage(UserMessageQueryModel messageQueryModel)
        {
            var loggedInUser = GetLoggedInUser();

            _userService.SaveUserMessage(
                new UserMessage()
                {
                    CreateDate = DateTime.Now,
                    Message = messageQueryModel.Message,
                    UserName = loggedInUser.UserName
                },
                loggedInUser.Id,
                messageQueryModel.ReceiverUserId);
            
            return RedirectToAction("GamePage",  new {messageQueryModel.CurrentGroup, messageQueryModel.CurrentTab});

        }

        [RequireLogin]
        public ActionResult SendGroupMessage(GroupMessageQueryModel groupMessage)
        {
            var group = _groupService.GetGroup(groupMessage.GroupId);
            var loggedInUser = GetLoggedInUser();

            if (group == null || loggedInUser == null)
                return RedirectToAction("GamePage");
            _groupService.SaveGroupMessage(
                new UserMessage()
                {
                    CreateDate = DateTime.Now,
                    UserName = loggedInUser.UserName,
                    Message = groupMessage.Message
                },
                loggedInUser.Id,
                group.Id);
            
            return RedirectToAction("GamePage", new { groupMessage.CurrentGroup, groupMessage.CurrentTab });

        }





        private LinkedUsers GetLinkedUsers(User loggedInUser, Group group)
        {
            var secretSantaUser = _userService.GetUser(group.GetPairWhereUserIsReceiver(loggedInUser.Id).SecretSantaId);
            var receiverUser = _userService.GetUser((group.GetPairWhereUserIsSecretSanta(loggedInUser.Id).ReceiverId));
            var secretSantaChat =
                _userService.GetUserMessages(MessageFilter.CreateUserConversationFilter(loggedInUser.Id,
                    secretSantaUser.Id));
            var receiverChat =
                _userService.GetUserMessages(MessageFilter.CreateUserConversationFilter(loggedInUser.Id,
                    receiverUser.Id));
            return new LinkedUsers()
            {
                LoggedInUser = loggedInUser,
                ReceiverUser = receiverUser,
                SecretSantaUser = secretSantaUser,
                SecretSantaConversation = GetMessageConversation(secretSantaChat, secretSantaUser.UserName),
                ReceivingUserConversation = GetMessageConversation(receiverChat)
            };
        }
        private IList<Message> GetMessageConversation( IList<UserMessage> messages,string anonymizeUsername ="" )
        {
            return messages.Select(
                msg => new Message()
                {
                    Sender = string.IsNullOrEmpty(anonymizeUsername) ? msg.UserName
                        : msg.UserName == anonymizeUsername ? "??" : msg.UserName,
                    Text = msg.Message,
                    CreateDate = msg.CreateDate
                }).ToList();
        }

        private User GetLoggedInUser()
        {
            var loggedInUser = _userService.GetUser(HttpContext.User.Identity.Name);
            if (loggedInUser == null)
                throw new AuthenticationException("No user named " + HttpContext.User.Identity.Name + " found");
            return loggedInUser;
            }
    }
}

api/SecretSanta/Views/Game/GameElements/AnonUserChat.cshtml
@model SecretSanta.WebUI.Controllers.Game.ViewModels.AnonUserChatViewModel
<script type="text/javascript">
    var objDiv = document.getElementsByClassName("chat");
    objDiv.scrollTop = objDiv.scrollHeight;
</script>
@if(Model.LoggedInUser != null){
    <div class="chat anon-chat">
        <table>
            <thead>
                <tr>
                    <th style="width: 1%">
                       
                    </th>
                    <th>
                    </th>
                    
                    <th style="width: 1%">
                       
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var msg in Model.Messages){
                    <tr>
                        <td>
                            <strong>@msg.Sender:</strong>
                        </td>
                        <td >
                            @msg.Text
                        </td>
                        <td style="border-left: dotted 1px;"><i>@msg.CreateDate.ToString("MM/dd HH:mm:ss")</i></td>
                    </tr>
                }
            </tbody>
        </table>
        </div>
    using (Html.BeginForm("SendUserMessage", "Game", FormMethod.Post))
    {
         @Html.Hidden("ReceiverUserId", Model.ReceiverUser.Id)
       <input type="hidden" name="CurrentTab" value="@Model.CurrentTab"/>
       <input type="hidden" name="CurrentGropu" value="@Model.CurrentGroup"/>

        <div class="input-group margin">
            <input type="text" name="message" class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    Sänd</button>
            </span>
        </div>
    }

}

api/SecretSanta/Views/Game/GameElements/GroupChat.cshtml
@using SecretSanta.RazorWebUI.Controllers.Game.ViewModels
@model SecretSanta.RazorWebUI.Controllers.Game.ViewModels.GroupChatViewModel
<script type="text/javascript">
    
    var objDiv = document.getElementsByClassName("group-chat");
    objDiv.scrollTop = objDiv.scrollHeight;
</script>

<div>
    <div class="chat group-chat">
        <table>
            <thead>
                <tr>
                    <th style="width: 1%">
                       
                    </th>
                    <th>
                    </th>
                    
                    <th style="width: 1%">
                       
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var msg in Model.Messages){
                    <tr>
                        <td>
                            <strong> @(msg.UserName.Equals(Model.SendingUserName, StringComparison.InvariantCultureIgnoreCase) ? "Du:" : msg.UserName)</strong>
                        </td>
                        <td>
                            @msg.Message
                        </td>
                        <td style="border-left: dotted 1px;"><i>@msg.CreateDate.ToString("MM/dd HH:mm:ss")</i></td>
                    </tr>
                }
            </tbody>
        </table>
        </div>
    @using (Html.BeginForm("SendGroupMessage", "Game", FormMethod.Post))
    {
        @Html.Hidden("groupId", Model.GroupId)
        <input type="hidden" name="CurrentGroup" value="@Model.CurrentGroup"/>
        <input type="hidden" name="CurrentTab" value="groupChat"/>
        <div class="input-group margin">
            <input type="text" name="message" class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    Sänd</button>
            </span>
        </div>
    }

    
        </div>

api/SecretSanta/Views/Game/GameElements/GroupChatPresenter.cshtml
@model SecretSanta.WebUI.Controllers.Game.ViewModels.GroupChatPresenterViewModel

<h4>Chatta med alla andra</h4>
<p>Här kan du chatta med alla andra som är med i <a href="#" data-toggle="modal" data-target="#@Model.GroupInformationModalViewModel.ModalId">din Hemliga Julklappstomtegrupp</a></p>

@Html.Partial("GameElements/GroupInformationModal", Model.GroupInformationModalViewModel)
<br/>
@Html.Partial("GameElements/GroupChat", Model.GroupChatViewModel)

api/SecretSanta/Views/Game/GameElements/GroupInformationModal.cshtml
@using SecretSanta.Core.Domain
@using SecretSanta.RazorWebUI.Controllers.Game.ViewModels
@model SecretSanta.RazorWebUI.Controllers.Game.ViewModels.GroupInformationModalViewModel

<div class="modal fade" id="@Model.ModalId" tabindex="-1" role="dialog" aria-labelledby="@Model.ModalId+Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="@Model.ModalId+Label">@Model.Group.Name</h4>
      </div>
      <div class="modal-body">
          <p>Gruppen @Model.Group.Name som du är med i @(Model.Group.Started.HasValue ? "startades " + @Model.Group.Started : "har ännu inte startat").</p>
          <p>Den består av dig och @(Model.Users.Count-1) andra deltagare:</p>
          <ul>
              @foreach (var user in Model.Users)
              {
                  <li>@user.UserName</li>
              }
          </ul>
          
            <img src="@Url.Content("~/images/Christmas-Gift-Christmas-smiley.gif")"/>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Stäng rutan</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

api/SecretSanta/Views/Game/GameElements/ReceivingUserPresenter.cshtml
@using SecretSanta.RazorWebUI.Helpers
@model SecretSanta.WebUI.Controllers.Game.ViewModels.ReceivingUserPresenterViewModel
<div class="">
    @if (Model.ReceivingUser != null)
    {
        <div class="text-center">
            <h4>
                Du har blivit utvald att ge en present till:</h4>
            <h2 class="receiving-user-text">@Model.ReceivingUser.FirstName @Model.ReceivingUser.LastName</h2>
            @if (Model.ReceivingUser.LastLoginDate.HasValue)
            {
                <p><i>Personens senaste besök: @Model.ReceivingUser.LastLoginDate.Value.ToShortDateString()</i></p>
            }
            else
            {
                <p>Personen har ALDRIG varit inne på den här sidan :/</p>
            }
            <img src="@Url.Content("~/images/girlang1.gif")"/>
        </div>
        <h4 class="underlined-text">
            @Model.ReceivingUser.FirstName Önskelista</h4>
        <ul class="wishlist">
            @foreach (var wish in Model.ReceivingUserWishlist)
            {
                <li>@wish.Description</li>
            }
        </ul>
        if (Model.ReceivingUserWishlist.IsNullOrEmpty())
        {
            <p>Din mottagare har inte lagt in någon önskelista :/</p>
        }
        <br/>
        <h4 class="under">Chatta anonymt med @Model.ReceivingUser.FirstName</h4>
        Model.AnonUserChatViewModel.CurrentTab ="chosen";
        @Html.Partial("GameElements/AnonUserChat", Model.AnonUserChatViewModel)
    }
    else
    {
        <p>Den här gruppen har inte startat sitt spel än!</p>
    }
</div>

api/SecretSanta/Views/Game/GameElements/UserWishlistPresenter.cshtml
@using SecretSanta.WebUI.Controllers.Game.ViewModels
@model SecretSanta.RazorWebUI.Controllers.Game.ViewModels.UserWishlistPresenterViewModel
<script type="text/javascript">
    $(document).ready(function () {
        $('.editable').editable({
            url: "Game/SaveOrUpdateWish",
            send: "always",
            mode: "popup",
            ajaxOptions: {
                contentType: 'application/json'
            },
            select2: {
                tokenSeparators: [","],
                tags: [],
                width: "resolve"
            },
            params: function (params) {

                var data = {};
                var editables = $(this).parents("tr").find("a");
                var activeEdit = $(this);

                $(editables).each(function () {
                    var paramName = $(this).attr("name");
                    data[paramName] = (activeEdit.attr("name") == paramName ? params.value : $(this).text());

                });
                data["UserName"] = '@Model.LoggedInUser.UserName';
                return JSON.stringify(data);
            }
        });
    });
</script>
<div>
    <h4>
        Din önskelista</h4>
    <p>
        Här kan du skriva en önskelista som din hemliga tomte kan se. Du kan även chatta med honom/henne, men du inte kommer kunna se vem det är.</p>
    <div class="well-lg background-color-white">
        <table style="margin-bottom: 5px"class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Önskan
                    </th>
                    <th style="width: 1%">
                        Ångra
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var wish in Model.LoggedInUserWishlist)
                {
                    <tr>
                        <td>
                            <a href="#" class="editable" data-type="text" data-title="Skriv in vad du vill ha"
                               name="Wish">@wish.Description</a> <a class="hidden" type="hidden" class="editable"
                                                                    name="WishId">@wish.Id</a>
                        </td>
                        <td>
                            @using (Html.BeginForm("DeleteWish", "Game", FormMethod.Post, new { @class = "text-center", style = "margin-bottom: 0px;" }))
                            {
                                @Html.Hidden("wishId", wish.Id)
                                <input type="hidden" name="CurrentTab" value="wishlist"/>
                                <input type="hidden" name="CurrentGropu" value="@Model.CurrentGroup"/>
                                <button type="submit" title="Ta bort önskan" class="btn btn-sm btn-danger">
                                    <i class="glyphicon glyphicon-remove"></i>
                                </button>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="">
            @using (Html.BeginForm("AddWish", "Game", FormMethod.Post))
            {
                <input type="hidden" name="CurrentTab" value="wishlist"/>
                <input type="hidden" name="CurrentGroup" value="@Model.CurrentGroup"/>
                <div class="input-group">
                    <input type="text" name="wish" class="form-control">
                    <span class="input-group-btn">
                        <button class="btn btn-success" type="submit">
                            Önska!</button>
                    </span>
                </div>
            }
        </div>
    </div>
</div>

@*<div>
    <h4 >Chatta med din hemliga tomte</h4>
    <p>Du kommer inte kunna se namnet på personen.</p>
    @{Model.AnonUserChatViewModel.CurrentTab = "wishlist";}
    @Html.Partial("GameElements/AnonUserChat", Model.AnonUserChatViewModel)
</div>*@